#!/bin/sh

# SPDX-FileCopyrightText: 2026 Univention GmbH
#
# SPDX-License-Identifier: AGPL-3.0-only

## joinscript api: bindpwdfile

#
#  Unjoin script that runs on the docker host.
#

VERSION=1

APP_ID="univention-consumer-template"

. /usr/share/univention-join/joinscripthelper.lib


main () {
	/usr/sbin/univention-provisioning-tool \
		unsubscribe \
		--subscription-file "/var/lib/univention-appcenter/apps/${APP_ID}/conf/provisioning/provisioning_config.json" \
		--provisioning-server $(hostname -f) || true
}


joinscript_init

main "$@"

joinscript_remove_script_from_status_file "$APP_ID"

exit 0
